"""version v1.6.1

Revision ID: f9f65bb2eb29
Revises: 8e8b08c34410
Create Date: 2024-04-24 20:26:21.162895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9f65bb2eb29'
down_revision: Union[str, None] = '8e8b08c34410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
