"""v1.6.6.1

Revision ID: cedf741f2d39
Revises: e6e9e98cb43e
Create Date: 2024-05-06 22:55:56.114538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cedf741f2d39'
down_revision: Union[str, None] = 'e6e9e98cb43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
