"""v1.6.6.4

Revision ID: 004ae70c8970
Revises: 54cb50b201c3
Create Date: 2024-05-07 15:48:51.182653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import *


# revision identifiers, used by Alembic.
revision: str = '004ae70c8970'
down_revision: Union[str, None] = '54cb50b201c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['category'])
    op.add_column('categoryoperationlink', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('categoryoperationlink', sa.Column('operation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categoryoperationlink', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'categoryoperationlink', 'operation', ['operation_id'], ['id'])
    op.create_unique_constraint(None, 'operation', ['operation'])
    op.add_column('transaction', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('category_operation_link_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'categoryoperationlink', ['category_operation_link_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'category_operation_link_id')
    op.drop_column('transaction', 'customer_id')
    op.drop_constraint(None, 'operation', type_='unique')
    op.drop_constraint(None, 'categoryoperationlink', type_='foreignkey')
    op.drop_constraint(None, 'categoryoperationlink', type_='foreignkey')
    op.drop_column('categoryoperationlink', 'operation_id')
    op.drop_column('categoryoperationlink', 'category_id')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
