"""v1.6.6.5

Revision ID: cb954c51c22f
Revises: 004ae70c8970
Create Date: 2024-05-07 15:56:34.320742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import *


# revision identifiers, used by Alembic.
revision: str = 'cb954c51c22f'
down_revision: Union[str, None] = '004ae70c8970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categoryoperationlink', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categoryoperationlink', type_='unique')
    # ### end Alembic commands ###
