"""version v1.0

Revision ID: 9bbf698c4d08
Revises: 
Create Date: 2024-04-14 21:56:45.729443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import *


# revision identifiers, used by Alembic.
revision: str = '9bbf698c4d08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('salary', 'home', 'health', 'sports', 'food', 'technology', 'cashback', 'gifts', 'other', name='categoryenum'), nullable=False),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoryoperationlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('income', 'outcome', name='operationenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('favourite_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favourite_category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('transaction')
    op.drop_table('operation')
    op.drop_table('categoryoperationlink')
    op.drop_table('category')
    # ### end Alembic commands ###
